// Loupe companion-spec generator.
//
// A finished Loupe Session persists as two faces of one artifact (ADR-0005):
//   - canonical: the portable HTML (the diagrams) — what `loupe new` produced.
//   - companion: a terse markdown spec next to it (decisions + a link back), for
//     the implementing agent to re-read and for version control.
//
// `loupe spec <file.html>` writes `<file>.spec.md` with the companion skeleton; the
// agent fills the `…` slots with the decisions the Session actually settled, then
// uses it as the source of truth while implementing.

import path from "node:path";

/** `foo/bar.html` -> `foo/bar.spec.md` */
export function deriveSpecPath(htmlFile) {
  const dir = path.dirname(htmlFile);
  const base = path.basename(htmlFile).replace(/\.html?$/i, "");
  return path.join(dir, `${base}.spec.md`);
}

/**
 * Render the companion spec skeleton.
 *
 * @param {{ title?: string, htmlBasename: string, productOnly?: boolean, greenfield?: boolean }} options
 * @returns {string} markdown
 */
export function createSpecMarkdown({
  title = "Untitled change",
  htmlBasename,
  productOnly = false,
  greenfield = false,
}) {
  let codeSection = "";
  if (!productOnly) {
    codeSection = greenfield
      ? `
## Code Lens (greenfield — from scratch)

- Proposed architecture (modules / interfaces to build): …
- Interfaces / contracts to add: …
- Grounded in: greenfield from-scratch (no existing codebase)
`
      : `
## Code Lens

- Architecture change (before → after): …
- Interface delta — added / changed / removed: …
- Grounded in: real codebase
`;
  }
  return `# ${title} — spec

> Canonical (visual review surface): [\`./${htmlBasename}\`](./${htmlBasename})
> Status: **approved** · generated by \`loupe spec\`

## Problem

…

## Product Lens

- Use cases touched (blast radius): …
- UX change (before → after): …
- Decisions settled in the grill: …
${codeSection}
## Open questions / follow-ups

- …
`;
}
